In [1]:
import pandas as pd 

df = pd.read_csv('/usr/share/dict/words')
# df = pd.read_csv('https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa.txt')
# df = pd.read_csv('https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt')
# df = pd.read_csv('http://www-personal.umich.edu/~jlawler/wordlist')
df.columns = ['Word']
df['Word'] = df['Word'].astype(str)
df.tail()

              Word
235880      zythem
235881      Zythia
235882      zythum
235883     Zyzomys
235884  Zyzzogeton

In [2]:
def num_letters(word):
    word = word.upper()
    letters = []
    for letter in word:
        if letter not in letters:
            letters.append(letter)
    return len(letters)
    
def len_word(word):
    return len(word)

In [3]:
df['Length'] = df['Word'].apply(len_word)
df['NLetters'] = df['Word'].apply(num_letters)
df['Ratio'] = df['NLetters'] / df['Length']

In [4]:
df[df['Word']=='senescence']

              Word  Length  NLetters  Ratio
178237  senescence      10         4    0.4

In [5]:
(df[df['Length']>3]
 .sort_values(by=['Ratio','Length','Word'], ascending=[True,False,True])
 .head(50)
)

                          Word  Length  NLetters     Ratio
49799                  deedeed       7         2  0.285714
230246              Wallawalla      10         3  0.300000
178290           senselessness      13         4  0.307692
101984            killeekillee      12         4  0.333333
102178            kinnikinnick      12         4  0.333333
197991            tangantangan      12         4  0.333333
7761                 anapanapa       9         3  0.333333
76056                   geggee       6         2  0.333333
100989                  kakkak       6         2  0.333333
176865                  seesee       6         2  0.333333
235682                  zoozoo       6         2  0.333333
182989          sleevelessness      14         5  0.357143
222559          unsensuousness      14         5  0.357143
60494   electrotelethermometer      22         8  0.363636
117512             Mississippi      11         4  0.363636
198334             taratantara      11         4  0.363636
96900         intertrinitarian      16         6  0.375000
144671        philophilosophos      16         6  0.375000
103031                Kukuruku       8         3  0.375000
160403                Purupuru       8         3  0.375000
14500                 assessee       8         3  0.375000
18421                 barabara       8         3  0.375000
30184                 caracara       8         3  0.375000
47075                 curucucu       8         3  0.375000
74780                 galagala       8         3  0.375000
75246                 ganggang       8         3  0.375000
102335                kivikivi       8         3  0.375000
102341                kiwikiwi       8         3  0.375000
102741                kolokolo       8         3  0.375000
112209                matamata       8         3  0.375000
117873                mocomoco       8         3  0.375000
120969                murumuru       8         3  0.375000
142035                pepperer       8         3  0.375000
147280                piripiri       8         3  0.375000
151171                poroporo       8         3  0.375000
162958                ramarama       8         3  0.375000
165483                referrer       8         3  0.375000
170155                riroriro       8         3  0.375000
195717                susurrus       8         3  0.375000
199263                teeterer       8         3  0.375000
203311                tikitiki       8         3  0.375000
204763                torotoro       8         3  0.375000
41609            consenescence      13         5  0.384615
97011            intestineness      13         5  0.384615
182961           sleeplessness      13         5  0.384615
200028           tenselessness      13         5  0.384615
41576       consciencelessness      18         7  0.388889
151433      possessionlessness      18         7  0.388889
10838     antitintinnabularian      20         8  0.400000
31439          catallactically      15         6  0.400000